service = [
		[
			{	'service-name':		'SVT-play',
			#	're'		:	r'(http://)?(www\.)?svtplay.se/(?P<url>.+)',
			#	'template'	:	'http://svtplay.se/%(url)s'},
				're'		:	r'(http://)?(www\.)?svtplay.se/(?P<path>(t|v)/\d+)',
				'template'	:	'http://svtplay.se/popup/minispelare/%(path)s'},
			#{	're'		:	r'(?:name="movie" value="(?P<swf_url>[^"]+)".*?)?(?P<url>rtmpe?://[^,]+),bitrate:(?P<bitrate>[0-9]+)',
			#{	're'		:	r'(?:name="movie" value="(?P<swf_url>[^"]+)".*subtitle=(?P<sub>[^&]+).*?)?(?P<url>rtmpe?://[^,]+),bitrate:(?P<bitrate>[0-9]+)',
			{	're'		:	r'(?:name="movie" value="(?P<swf_url>[^"]+)".*?)?(?P<url>rtmpe?://[^,]+),bitrate:(?P<bitrate>[0-9]+)(?=.*?subtitle=(?P<sub>[^&]*))',
				'template'	:	'#quality: %(bitrate)s kbps; subtitles: %(sub)s;\nrtmpdump --swfVfy http://svtplay.se%(swf_url)s -r %(url)s -o %(output_file)s'}],
		[#SVT-play-alternate/flv clip
			{	're'		:	r'(http://)?(www\.)?svtplay.se/(?P<url>.+)',
				'template'	:	'http://svtplay.se/%(url)s'},
			#{	're'		:	r'(http://)?(www\.)?svtplay.se/(?P<path>(t|v)/\d+)',
			#	'template'	:	'http://svtplay.se/popup/minispelare/%(path)s'},
			{	're'		:	r'pathflv=(?P<url>http?://[^&]+)',
				'template'	:	'#\n%(url)s'}],
		[#SVT-play-alternate/flv clip-rtmp
			{	're'		:	r'(http://)?(www\.)?svtplay.se/(?P<url>.+)',
				'template'	:	'http://svtplay.se/%(url)s'},
			{	're'		:	r'(?:name="movie" value="(?P<swf_url>[^"]+)".*?)pathflv=(?P<url>rtmpe?://[^&]+)',
				'template'	:	'#\nrtmpdump -W "http://svtplay.se%(swf_url)s" -r "%(url)s" -o %(output_file)s'}],
		[
			{	'service-name':		'SR',
				're'		:	r'(http://)?(www\.)?sverigesradio.se/(?P<url>.+)',
				'template'	:	'http://sverigesradio.se/%(url)s'},
			{	're'		:	r'<ref href="(?P<url>[^"]+)"',
				'template'	:	'#\n%(url)s'}],
		[
			{	'service-name':		'UR-play',
				're'		:	r'(http://)?(www\.)?urplay.se/(?P<url>.+)',
				'template'	:	'http://urplay.se/%(url)s'},
			{	're'		:	r'file=/(?P<url>[^&]+(?P<ext>mp[34]))(?:.*?captions.file=(?P<sub>[^&]+))?',
				'template'	:	'#subtitles: %(sub)s;\nrtmpdump -r rtmp://streaming.ur.se/ -y %(ext)s:/%(url)s -a ondemand -o %(output_file)s'}],
		[
			{	'service-name':		'TV4-play',
				're'		:	r'(http://)?(www\.)?tv4play.se/.*videoid=(?P<id>\d+).*',
				'template'	:	'http://premium.tv4play.se/api/web/asset/%(id)s/play'},
			{	're'		:	r'(<playbackStatus>(?P<status>\w+).*?)?<bitrate>(?P<bitrate>[0-9]+)</bitrate>.*?(?P<base>rtmpe?://[^<]+).*?(?P<url>mp4:/[^<]+)(?=.*?(?P<sub>http://anytime.tv4.se/multimedia/vman/smiroot/[^<]+))?',
				'template'	:	'#quality: %(bitrate)s kbps; subtitles: %(sub)s;\nrtmpdump -W http://www.tv4play.se/flash/tv4playflashlets.swf -r %(base)s -y %(url)s -o %(output_file)s'}],
		[
			{	'service-name':		'MTG',
				're'		:	r'(http://)?(www\.)?tv[368]play.se/.*(?:play/(?P<id>\d+)).*',
				'template'	:	'http://viastream.viasat.tv/PlayProduct/%(id)s'},
			{	're'		:	r'<SamiFile>(?P<sub>[^<]*).*<Video>.*<BitRate>(?P<bitrate>\d+).*?<Url><!\[CDATA\[(?P<url>rtmp[^\]]+)',
				'template'	:	'#quality: %(bitrate)s kbps; subtitles: %(sub)s;\nrtmpdump -W http://flvplayer-viastream-viasat-tv.origin.vss.viasat.tv/play/swf/player110420.swf -r %(url)s -o %(output_file)s'}],
		[#MTG-alternate
			{	're'		:	r'(http://)?(www\.)?tv[368]play.se/.*(?:play/(?P<id>\d+)).*',
				'template'	:	'http://viastream.viasat.tv/PlayProduct/%(id)s'},
			{	're'		:	r'<SamiFile>(?P<sub>[^<]*).*<Video>.*<BitRate>(?P<bitrate>\d+).*?<Url><!\[CDATA\[(?P<url>http[^\]]+)',
				'template'	:	'%(url)s'},
			{	're'		:	r'<Url>(?P<url>[^<]+)',
				'template'	:	'#quality: %(bitrate)s kbps; subtitles: %(sub)s;\nrtmpdump -W http://flvplayer-viastream-viasat-tv.origin.vss.viasat.tv/play/swf/player110420.swf -r %(url)s -o %(output_file)s'}],
		[
			{	'service-name':		'Aftonbladet-TV',
				're'		:	r'(http://)?(www\.)?aftonbladet.se/(?P<url>.+)',
				'template'	:	'http://aftonbladet.se/%(url)s'},
			{	're'		:	'videoUrl:\s"(?P<base>rtmp://(ss11i04.stream.ip-only.net|fl1.c00862.cdn.qbrick.com)/[^/]+/)(?P<url>[^"]+)"',
				'template'	:	'#\nrtmpdump -r %(base)s -y %(url)s -o %(output_file)s'}],
		[
			{
				'service-name':		'Vimeo',
				'headers':		{'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.36 (KHTML, like Gecko) Chrome/13.0.766.0 Safari/534.36'},
				're'		:	r'(http://)?(www\.)?vimeo.com/(?P<url>.+)',
				'template'	:	'http://vimeo.com/%(url)s'},
			{
				'headers':		{'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.36 (KHTML, like Gecko) Chrome/13.0.766.0 Safari/534.36'},
				're'		:	r'"signature":"(?P<sig>[^"]+)".*?timestamp":(?P<time>\d+).*?h264":\["(?P<quality>[^"]+)',
				'template'	:	'http://player.vimeo.com/play_redirect?clip_id=%(url)s&sig=%(sig)s&time=%(time)s&quality=%(quality)s&codecs=H264,VP8,VP6&type=moogaloop_local&embed_location='},
			{
				'headers':		{'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.36 (KHTML, like Gecko) Chrome/13.0.766.0 Safari/534.36'},
				're'		:	r'Location: (?P<url>.*?)\n',
				'template'	:	'#quality: %(quality)s;\n%(url)s'}],
		[
			{	'service-name':		'Kanal5-play, Kanal9-play',
				're'		:	r'(http://)?(www\.)?kanal(?P<n>5|9)play.se/(?P<url>.+)',
				'template'	:	'http://kanal%(n)splay.se/%(url)s'},
			{	're'		:	r'@videoPlayer" value="(?P<video_player>[^"]+)"',
				'template'	:	'kanal5://%(video_player)s'},
			{
				're'		:	r'"(?P<height>\d+)x(?P<width>\d+):(?P<URL>[^&]+)&(?P<path>[^"]+)";',
				'template'	:	'#quality: %(height)sx%(width)s;\nrtmpdump --swfVfy http://admin.brightcove.com/viewer/us1.25.04.01.2011-05-24182704/connection/ExternalConnection_2.swf -r %(URL)s -y %(path)s -o %(output_file)s'}],
		[
			{	're':			r'(http://)?(www\.)?redtube.com/(?P<path>.+)',
				'template':		'http://redtube.com/%(path)s'},
			{	're':			'<source src="(?P<url>[^"]+)"',
				'template':		'#\n%(url)s'}],
		[
			{	'service-name':		'Axess-TV',
				're'		:	r'(http://)?(www\.)?axess.se/(?P<url>.+)',
				'template'	:	'http://axess.se/%(url)s'},
			{	're'		:	r'url: \'(?P<url>[^\']+)\'.*netConnectionUrl: \'(?P<base>[^\']+)',
				'template'	:	'#\nrtmpdump -r %(base)s -y %(url)s -o %(output_file)s'}],
		[
			{	'service-name':		'VGTV',
				're':			r'(http://)?(www\.)?vgtv.no/#!?id=(?P<id>\d+)',
				'template':		'http://www.vgtv.no/data/actions/videostatus/?id=%(id)s'},
			{	're':			r'"bitrate":(?P<bitrate>\d+).*?"address":"(?P<address>[^"]+)","port":80,"application":"","path":"download\\(?P<path1>[^\\]+)\\(?P<path2>[^\\]+).*?","filename":"(?P<filename>[^"]+)"',
				'template':		'#quality: %(bitrate)s\nhttp://%(address)s:80/download%(path1)s%(path2)s/vgtv/streaming/compressed/%(id)s/%(filename)s'}],
		[
			{	'service-name':		'ABF-play',
				're':			r'(http://)?(www\.)?abfplay.se/#(?P<id>.+)',
				'template':		'http://csp.picsearch.com/rest?jsonp=ps.responseHandler&eventParam=3&auth=r4MlmWY4CCH4AS_Z41gYqik4B37w5SQxkPkTiN2zCLqY8abCNEEDvA&method=embed&containerId=mediaplayer&mediaid=%(id)s&autoplay=true&player=rutile&width=620&height=430'},
			{	're':			r'"url": "rtmp%3A//rtmp.picsearch.com/content/(?P<url>[^"]+)%3F',
				'template':		'#\nrtmpdump -r rtmp://rtmp.picsearch.com/content -a content -W http://csp.picsearch.com/players/rutile.swf -y %(url)s -o %(output_file)s'}],
		[
			{	'service-name':		'Youtube',
				're':			r'(http://)?(www\.)?youtube.com/(?P<url>.+)',
				'template':		'http://youtube.com/%(url)s'},
			{	're':			r'url%3D(?P<url>.*?)%26quality%3D(?P<quality>.*?)%26',
				'template':		'#quality: %(quality)s\n%(url)s',
				'decode-url':		2}],
		[
			{	'service-name':		'NRK',
				'headers':		{'Cookie': 'NetTV2.0Speed=7336'},
				're':			r'(http://)?(www\.)?nrk.no/nett-tv/(?P<url>.+)',
				'template':		'http://nrk.no/nett-tv/%(url)s'},
			{	're':			r'name="Url" value="(?P<url>[^"]+)',
				'template':		'%(url)s'},
			{	're':			r'href="(?P<url>mms://[^"]+)"',
				'template':		'#\n%(url)s'}]]